[workspace]
members = ["core", "cli", "daemon"]
default-members = ["cli"]
resolver = "2"

[workspace.dependencies]
pge = { git = "https://github.com/puppycorp/pge.git", rev = "28e7752d9da9c7c683810186a401fcd6284c5814"}
